### ISSUE TITLE
[CURVE]: 3D and 2D draw functions do not differentiate between 3D and 2D points

### ISSUE THREAD

**Issue by leeyi45** [source-academy/modules#130]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

2D Draw methods should throw an error when passed a 3D curve, and 3D draw methods should throw
an error when passed a 2D curve.

# Current Behavior

The 2D draw methods like `draw_connected` accept 3D points created by `make_3D_point`, and 
3D draw methods like `draw_3D_connected` accept 2D points created by `make_2D_point`.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

```.ts
import { draw_connected, draw_3D_connected, make_point, make_3D_point } from 'curve';

draw_connected(200)(t => make_3D_point(t, t, t)); // works with no error
draw_3D_connected(200)(t => make_point(t, t)); // works with no error
```

**Comment by martin-henz** [comment]
Why is this an error and not a feature?

**Comment by leeyi45** [comment]
> Why is this an error and not a feature?
While working on the original implementation for curve animations I needed to be able to distinguish between both, but my later implementations no longer require this distinction
