### ISSUE TITLE
Upgrade blueprint js version in modules repository to match frontend

### ISSUE THREAD

**Issue by chownces** [source-academy/modules#152]
I noticed that the frontend and modules repo had different versions of @blueprintjs, resulting in weird behaviour when tabs were rendered. Possibly need to look into how we can update blueprint in the modules repo if it is updated in the frontend

_Originally posted by @leeyi45 in https://github.com/source-academy/modules/issues/148#issuecomment-1223582782_

Example:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/53928333/187597735-5bbaac3d-5eb0-434c-b635-46d1fef70925.png">

**Comment by Cloud7050** [comment]
BlueprintJS upgraded V3→V4 in #153, alongside some other packages since the new build system worked with ESM, such as chalk & lowdb.
