### ISSUE TITLE
[RUNE]: heart has too low resolution

### ISSUE THREAD

**Issue by martin-henz** [source-academy/modules#170]
The heart rune is currently ugly because it doesn't have enough resolution. The edges of the polygon are clearly visible. Example:

https://share.sourceacademy.org/7gbki

<img width="712" alt="Screen Shot 2023-01-30 at 10 45 11 AM" src="https://user-images.githubusercontent.com/30220768/215377090-0b26ecb5-207b-4530-90a3-21f3f95025e9.png">

Compare with the ribbon, which has sufficient resolution.

**Comment by Cloud7050** [comment]
When I took CS1101S, I seem to recall seeing earlier screenshots where the heart rune had indistinguishably smooth edges. However, the module we were learning with already had the low resolution heart, and has since stayed this way. Did something change in the past, perhaps for performance reasons?

**Comment by martin-henz** [comment]
> When I took CS1101S, I seem to recall seeing earlier screenshots where the heart rune had indistinguishably smooth edges. However, the module we were learning with already had the low resolution heart, and has since stayed this way. Did something change in the past, perhaps for performance reasons?

Yes, this is a regression. We had a higher-resolution heart before, and I don't think there are performance reasons.

**Comment by Cloud7050** [comment]
The fix involves changing a number from `10` to `100`. I will have this in my upcoming PR.

![image](https://github.com/source-academy/modules/assets/44526554/520c85cb-03a3-468f-b42f-5efd4e807c6d)
