### ISSUE TITLE
[CSG 2.0]: Side buttons not clickable

### ISSUE THREAD

**Issue by RichDom2185** [source-academy/modules#214]
# Prerequisites

Run any program that renders the CSG tab.

# Expected Behavior

Side buttons would be clickable.

# Current Behavior

Side buttons cannot be interacted with (except hover, which shows the tooltip). One can still use the mouse controls given in those tooltips to interact with the "canvas" directly.

![image](https://github.com/source-academy/modules/assets/34370238/9b04da3f-77dd-4eeb-b225-5dbeb0a0cad6)

## Context

- Version used:  f72e5a14be62e9eaca7b9a165c0ff7e1aaa76558
- Browser Name and version: Chrome 113
- Operating System and version (desktop or mobile): macOS 13.4 (arm64)

**Comment by Cloud7050** [comment]
Click functionality was not added to the hints in V1 (Cloud7050/modules#23). There are a few remaining enhancements/bugs left over from CSG V1 which live as issues in its fork. I'm not fully aware of what V2 planned to implement.

But on a related note, the tooltips should be changed to use BlueprintJS ones as I heard we have the technology for modules to do so now. The current ones were custom CSS that would sometimes float strangely depending on the width of the sidebar.

**Comment by Cloud7050** [comment]
See also #229
