### ISSUE TITLE
[Bundles]: Unable to change modules without refreshing.

### ISSUE THREAD

**Issue by yongxiangng** [source-academy/modules#22]
Unable to change modules without refreshing. For example, if I first import from repeat, it works fine. Without refreshing, if I import curve again, it doesn't work.

<img width="1440" alt="Screenshot 2021-03-22 at 1 29 16 PM" src="https://user-images.githubusercontent.com/60974969/111944667-25d09c00-8b13-11eb-92d3-18f7d3cf42d2.png">

<img width="1440" alt="Screenshot 2021-03-22 at 1 29 57 PM" src="https://user-images.githubusercontent.com/60974969/111944736-47ca1e80-8b13-11eb-852b-4a6f68c1c839.png">

under `src/bundles/curve/index.ts` I defined curve as this.
```
function curve() {
  return 'curve';
}
```
If I call `curve()` it says `Line 2: Calling non-function value undefined.`

Note:
Same issues arises if I import curve then import repeat.
Issue does not arise if I try to change the functions I want to import from within the same module.

**Comment by Anonymxtrix** [comment]
It turns out that the fix to this issue is the same as that to issue #23. Refer to issue #23 for the detailed explanation.
