### ISSUE TITLE
Better name choice for math_log.

### ISSUE THREAD

**Issue by yiwen101** [source-academy/modules#226]
Currently, the math_log function computes the natural logarithm of the input x. It is good to consider renaming this function to math_ln, so that there is less confusion.

**Comment by martin-henz** [comment]
Source is a sublanguage of JavaScript and all math_ functions match the JavaScript Math. functions. For Math.log, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log

**Comment by RichDom2185** [comment]
>  Currently, the math_log function computes the natural logarithm of the input x. It is good to consider renaming this function to math_ln, so that there is less confusion.

Just to add on, correct me if I'm wrong buy I believe "ln" and "lg" are terms that are specific only to Singapore and its education system (perhaps for disambiguation reason). I believe in most parts of the world, "log" without a base refers to the natural logarithm (hence "natural"), while "log base 10" is written like any other base using "log_10".

**Comment by Cloud7050** [comment]
> > Currently, the math_log function computes the natural logarithm of the input x. It is good to consider renaming this function to math_ln, so that there is less confusion.
> 
> Just to add on, correct me if I'm wrong but I believe "ln" and "lg" are terms that are specific only to Singapore and its education system (perhaps for disambiguation reasons). I believe in most parts of the world, "log" without a base refers to the natural logarithm (hence "natural"), while "log base 10" is written like any other base using "log_10".

Wow, that would explain something I encountered in a math module with a TA from another country.
