### ISSUE TITLE
[Tabs]: Spawn Tab does not change name when modules are changed

### ISSUE THREAD

**Issue by yongxiangng** [source-academy/modules#23]
Not sure if this issue is related to previous issue, but when I change the module I'm importing from, the spawn tab's tag does not change. For example. if I import something from repeat module, then import from another module, the spawn tab's tag remains as Repeat Test Tab.

<img width="1440" alt="Screenshot 2021-03-22 at 1 29 16 PM" src="https://user-images.githubusercontent.com/60974969/111945343-86140d80-8b14-11eb-8528-7bbf46bc3b7f.png">

<img width="1440" alt="Screenshot 2021-03-22 at 1 29 57 PM" src="https://user-images.githubusercontent.com/60974969/111945362-8f04df00-8b14-11eb-91e0-9fea9f3f8a61.png">

Maybe this issue is related to the previous one and would be fixed simultaneously.

Edit: other spawn tab bugs 
<img width="1440" alt="Screenshot 2021-03-22 at 1 50 35 PM" src="https://user-images.githubusercontent.com/60974969/111945968-9d9fc600-8b15-11eb-8c88-31a12de90f60.png">

- I cannot concurrently import 2 modules.
- The functions from the 2nd modules are all undefined.
- 2 Spawn tabs appear but both have the same tag (Repeat Test Tab)
- 2nd spawn tab is unclickable

**Comment by Anonymxtrix** [comment]
I found the cause of the bug. 

From [here](https://dev.to/nioufe/you-should-not-use-lodash-for-memoization-3441), it states that lodash `memoize()` only uses the first parameter. In our memoized `memoizedGetModuleFile` function in `js-slang`'s `moduleLoader.ts`, our `memoizedGetModuleFile('bundle', path)` function's first parameter remains the same regardless of the `bundle`'s or `tab`'s name. As a result, calling the function on `Repeat` and `RepeatTwo` `tabs` will result in the memoized function returning the first call's result on the second call.

**Comment by Anonymxtrix** [comment]
See the pull request [here ](https://github.com/source-academy/js-slang/pull/916/checks?check_run_id=2178454505)for the fix.
