### ISSUE TITLE
[CSG]: Recent changes broke patch's colorizePolygons

### ISSUE THREAD

**Issue by Cloud7050** [source-academy/modules#265]
When attempting to run the [snowglobe sample](https://github.com/Cloud7050/modules/blob/949de19003be2b935e44727f11f9ee5913dd990c/src/bundles/csg/samples/snowglobe.js), the following error is shown in the REPL:

> Line 11: ReferenceError: colorizePolygons is not defined

That name occurs in the JSCAD modelling library's patch file. It would appear that recent changes in master may have broken the CSG module.

Line 11 calls `intersect()` from the CSG module. A trivial example such as `render(cube(silver))` still works without error.

**Comment by Cloud7050** [comment]
@leeyi45 would you happen to know of anything related to the build system that may have changed recently such that this would be impacted?

**Comment by martin-henz** [comment]
I can confirm that the problem exists as of today, in sourceacademy.org. Here is the direct share link: https://share.sourceacademy.org/ab906

**Comment by leeyi45** [comment]
I bumped the version of `esbuild`, that is the only possible breaking change that comes to mind

**Comment by joeng03** [comment]
Update: `render(cube(silver))` also does not currently work at https://share.sourceacademy.org/ab906

**Comment by joeng03** [comment]
@leeyi45 when was the version on `esbuild` bumped?

**Comment by Cloud7050** [comment]
> @leeyi45 at which commit was the version on `esbuild` bumped?

Likely in cad882252cfd1defc53c78fa4367cef9ef395877.

https://github.com/source-academy/modules/pull/244/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L62-R73

**Comment by joeng03** [comment]
> I am currently able to run it:

Yep, could also run it locally, but not on the website

**Comment by Cloud7050** [comment]
> Yep, could also run it locally, but not on the website

I followed the share link and edited it there. So it was actually running on sourceacademy.org.

Testing on both deployments, neither org nor NUS can run the snowglobe snippet, but they can run the cube.

If the snowglobe works locally, perhaps that's a clue?
