### ISSUE TITLE
[Curves]: Dependencies not exporting functions correctly

### ISSUE THREAD

**Issue by zhenghanlee** [source-academy/modules#39]
# Prerequisites

I require "debounce" dependency for "three" and "three-react-fiber". The package supposedly exports "debounce" function as follows:

![Screenshot 2021-03-29 at 3 38 50 PM](https://user-images.githubusercontent.com/75558451/112803374-c8ee5c00-90a5-11eb-9079-f35b6fbca9f8.png)

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Current Behavior

The project is unable to build.

# Failure Information (for bugs)

![Screenshot 2021-03-29 at 3 39 21 PM](https://user-images.githubusercontent.com/75558451/112803068-7d3bb280-90a5-11eb-94f8-d11c16bdc205.png)

## Steps to Reproduce

1. Checkout to graphics/three-react-fiber
2. Run `yarn install` to install all additional dependencies required
3. Run `yarn build`

## Context

- Version used: 753176e
- Browser Name and version: N.A.
- Operating System and version (desktop or mobile): macOS Catalina version 10.15.7

**Comment by zhenghanlee** [comment]
There is a similar issue for the `react-three-fiber` package as well.
![Screenshot 2021-03-29 at 4 01 56 PM](https://user-images.githubusercontent.com/75558451/112805411-22f02100-90a8-11eb-8a59-3cd2c6594a4e.png)

**Comment by Anonymxtrix** [comment]
Very tilted at this issue!!! Can't seem to fix... @zhenghanlee 

Plausible problems identified so far:
- `rollup-plugin-common-js` is deprecated, use `@rollup/plugin-commonjs` instead
- `react-three-fiber` or `@react-three/fiber`??? I also not sure but you have a dependency for the latter from `@react-three/drei`
- `injectProcessEnv()` needs to go all the way to the top of the `plugins[]` in `rollup.config.js`
- Order of `plugins` should be `injectProcessEnv(), resolve(), commonjs(), babel(), ...`

**Comment by zhenghanlee** [comment]
I think this issue can be closed as the graphics team will no longer be looking into the use of ThreeJS or other relevant packages, at least not in near future.
