### ISSUE TITLE
[WIKI]: Documentation for RollupJS bundler

### ISSUE THREAD

**Issue by Anonymxtrix** [source-academy/modules#43]
# Feature

Ever since the introduction of our module bundler RollupJS, I feel that documenting in the code alone is insufficient. We should include a page in the wiki to explain the choices and the build flow (eg. `TypeScript -> ESNext -> ES2015`) and the intermediate steps within the bundler system (eg. `CopyFilePlugin` and `Polyfills`). 

## Checklist

- [x] I checked the documentation and found that it does not already exist
- [x] I checked to make sure that this issue has not already been filed

**Comment by Cloud7050** [comment]
With the introduction of the new build system, rollup.js is no longer used (in favour of the much faster esbuild) and the build process has thus changed.
