### ISSUE TITLE
[Wiki]: Advanced Developer guide

### ISSUE THREAD

**Issue by MarcusTXK** [source-academy/modules#46]
# Feature

Add a guide to teach creators of modules on how to pass functions from the bundle to the front end.
This is for more complex modules that require interactions with the tab's content (eg. curves, pixNFlix) or user interaction (eg. buttons)

## Checklist

- [x] I checked the documentation and found that it does not already exist
- [x] I checked to make sure that this issue has not already been filed

**Comment by Anonymxtrix** [comment]
See [here](https://github.com/source-academy/modules/wiki/FAQs#could-you-explain-more-on-the-infrastructure-of-the-modules-system-especially-regarding-how-the-bundle-and-tabs-communicate)

**Comment by Anonymxtrix** [comment]
This has been completed, so im closing the issue. See [here](https://github.com/source-academy/modules/wiki/System-Implementation-in-Source-Academy-Frontend#interaction-with-the-source-modules-bundle).
