### ISSUE TITLE
Use of IMPORT for hidden prepended functions

### ISSUE THREAD

**Issue by geshuming** [source-academy/modules#5]
Now that we have an IMPORT node, I think we can load symbols from external libraries so that we achieve the effect of prepending functions while hiding their implementation.

We can still keep the PREPEND node for prepend programs that do not need to be hidden.

**Comment by martin-henz** [comment]
I agree. But this is postponed till 20/21.

**Comment by martin-henz** [comment]
I dont think there is anything actionable in this Issue.
