### ISSUE TITLE
[Modules]: Change `__params` into a global variable

### ISSUE THREAD

**Issue by Anonymxtrix** [source-academy/modules#56]
# Feature

Is your feature request related to a problem? Please describe.

I'm always frustrated when TypeDoc API generator requires functions/mock functions to be defined in `functions.ts` in the root directory of the Source Module Bundles.

I would like to change the default export function in Source Module Bundle's `index.ts` to regular `export function ...` for every function provided by the Source Module. The `__params` should be changed into a **global variable** (ie. `__dirname`). 

## Checklist

- [x] I checked the requested feature does not already exist
- [x] I checked to make sure that this issue has not already been filed

**Comment by leeyi45** [comment]
Issue has since been resolved by #126, #148, #153 and #163
