### ISSUE TITLE
[MODULES]: wrong names are silently ignored

### ISSUE THREAD

**Issue by martin-henz** [source-academy/modules#78]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

Importing of wrong names should give an error.

# Current Behavior

Wrong names are silently ignored. The name is get_wave, not fetch_wave:

<img width="741" alt="Screenshot 2021-07-09 at 3 25 16 PM" src="https://user-images.githubusercontent.com/30220768/125040579-6a844100-e0ca-11eb-8ed5-89614f94a099.png">

# Failure Information (for bugs)

-

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

See above

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

Current sourceacademy.org, Chrome on macOS.

## Failure Logs

see above

**Comment by leeyi45** [comment]
Resolved by [this PR to js-slang](https://github.com/source-academy/js-slang/pull/1388)
