### ISSUE TITLE
[rune]: corner case of overlay_frac

### ISSUE THREAD

**Issue by martin-henz** [source-academy/modules#97]
<img width="961" alt="Screenshot 2021-08-24 at 4 56 35 PM" src="https://user-images.githubusercontent.com/30220768/130588272-b5392669-7d88-4b97-be1c-76730136c0b8.png">

The heart should be on top of the triangle.

**Comment by martin-henz** [comment]
Let's change this after the rune contest deadline: 31/8. @houruomu please take note.

**Comment by houruomu** [comment]
Noted. Thanks.

**Comment by martin-henz** [comment]
@houruomu we need to wait until contest voting is over, to fix this.
